<?php
$z[0]=Array("top","\r\n    <m:item name='模块管理' link='module_main.php' rank='sys_module' target='main' />\r\n    <m:item name='上传新模块' link='module_upload.php' rank='sys_module' target='main' />\r\n    <m:item name='模块生成向导' link='module_make.php' rank='sys_module' target='main' />\r\n    ",51,399);
$z[0][4]=array();
$z[0][4]['name']="模块管理";
$z[0][4]['c']="6,";
$z[0][4]['display']="block";
$z[1]=Array("top","\r\n  <m:item name='插件管理器' link='plus_main.php' rank='10' target='main' />\r\n  <m:item name='文件管理器' link='file_manage_main.php' rank='plus_文件管理器' target='main' />\r\n<m:item name='广告管理' link='ad_main.php' rank='plus_广告管理' target='main' />\r\n<m:item name='友情链接' link='friendlink_main.php' rank='plus_友情链接模块' target='main' />\r\n\r\n",401,848);
$z[1][4]=array();
$z[1][4]['item']="7";
$z[1][4]['name']="辅助插件";
$z[1][4]['display']="block";
$z[2]=Array("top","\r\n<m:item name='畅言模块' link='changyan_main.php' rank='sys_Feedback' target='main'/>\r\n<m:item name='评论管理' link='changyan_main.php?dopost=manage' rank='sys_Feedback' target='main'/>\r\n<m:item name='数据统计' link='changyan_main.php?dopost=stat' rank='sys_Feedback' target='main'/>\r\n<m:item name='导入导出' link='changyan_main.php?dopost=import' rank='sys_Feedback' target='main'/>\r\n<m:item name='畅言设置' link='changyan_main.php?dopost=setting' rank='sys_Feedback' target='main'/>\r\n",852,1410);
$z[2][4]=array();
$z[2][4]['name']="畅言评论";
$z[2][4]['display']="block";
$z[3]=Array("top","\r\n<m:item name='插件安装步骤' link='ckplayer_main.php' rank='' target='main' />\r\n<m:item name='插件基本参数' link='ckplayercommon_main.php' rank='' target='main' />\r\n<m:item name='关于ckplayer插件' link='ckplayer_about.php' rank='' target='main' />\r\n<m:item name='ckplayer风格下载' link='ckplayer_dlstyle.php' rank='' target='main' />\r\n",1412,1839);
$z[3][4]=array();
$z[3][4]['name']="ckplayer播放器";
$z[3][4]['c']="6,";
$z[3][4]['display']="block";
$z[3][4]['rank']="";

?>