<a href="xxx.html" class="hvr-shutter-out-horizontal"><img src="{dede:global.cfg_templets_skin/}/img/yande.re 424097 sample landscape niko_p signed thighhighs umbrella.jpg" title="xxx-name" class="img-responsive" alt=" " />
									<div class="w3l-action-icon"><i class="glyphicon glyphicon-play-circle" aria-hidden="true"></i></div>
								</a>
								<div class="wenzi">
									<div class="w3l-movie-text">
										<h6><a href="xxx.html">[field:title/]</a></h6>							
									</div>
									<div class="mid-2">
										<p> [field name/ function='GetDateMk(@me)'/]</p>
									</div>
								</div>
								<div class="ribben">
								  <p>NEW</p>
								</div>