<li>
						<a href="[field:arcurl/]" class="hvr-shutter-out-horizontal">
							<img src="[field:litpic/]" title="xxx-name" class="img-responsive" alt=" " />
							<div class="w3l-action-icon"><i class="glyphicon glyphicon-play-circle" aria-hidden="true"></i></div>
						</a>
						<h6><a href="[field:arcurl/]">[field:title/]</a></h6>
						<p>[field:pubdate function="GetDateTimeMK(@me)"/]</p>
					</li>