<field:video_address itemname="播放源" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:video_address>
<field:shipinjieshao itemname="视频介绍" autofield="1" notsend="0" type="htmltext" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:shipinjieshao>

<field:praise itemname="获奖情况" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:praise>
