<?php
$z[0]=Array("global","",61,88);
$z[0][4]=array();
$z[0][4]['name']="cfg_basehost";
$z[1]=Array("global","",99,124);
$z[1][4]=array();
$z[1][4]['name']="cfg_cmsurl";
$z[2]=Array("field","",139,173);
$z[2][4]=array();
$z[2][4]['name']="video_address";
$z[3]=Array("field","",190,224);
$z[3][4]=array();
$z[3][4]['name']="html5_address";
$z[4]=Array("field","",236,255);
$z[4][4]=array();
$z[4][4]['name']="title";
$z[5]=Array("field","",268,288);
$z[5][4]=array();
$z[5][4]['name']="litpic";
$z[6]=Array("field","global \$cfg_cmsurl;if(@me == ''){@me = '';}else{\r\n@me = '<script type=\"text/javascript\" src=\"'.\$cfg_cmsurl.'/ckplayer/static/js/offlights.js\"></script>'.chr(13);\r\n@me .= '<script type=\"text/javascript\" src=\"'.\$cfg_cmsurl.'/ckplayer/static/player/ckplayer.js\"></script>'.chr(13);\r\n@me .= '<script type=\"text/javascript\">document.write(\"<div id=\\\"a1\\\" style=\\\"position:relative;z-index:100;clear:both;\\\"></div>\")</script>'.chr(13);\r\n@me .= '<script type=\"text/javascript\" src=\"'.\$cfg_cmsurl.'/ckplayer/static/js/player_pc.js\"></script>';}\r\n",356,960);
$z[6][4]=array();
$z[6][4]['name']="video_address";
$z[6][4]['runphp']="yes";

?>