<?php
$z[0]=Array("global","",30,59);
$z[0][4]=array();
$z[0][4]['name']="cfg_soft_lang";
$z[1]=Array("global","global \$cfg_basehost,\$cfg_cmsurl; if(!strstr(\$cfg_cmsurl,'http://')){@me = \$cfg_basehost.\$cfg_cmsurl;}else{@me = \$cfg_cmsurl;}",104,292);
$z[1][4]=array();
$z[1][4]['name']="cfg_cmsurl";
$z[1][4]['runphp']="yes";
$z[2]=Array("global","global \$cfg_basehost,\$cfg_cmsurl; if(!strstr(\$cfg_cmsurl,'http://')){@me = \$cfg_basehost.\$cfg_cmsurl;}else{@me = \$cfg_cmsurl;}",523,711);
$z[2][4]=array();
$z[2][4]['name']="cfg_cmsurl";
$z[2][4]['runphp']="yes";
$z[3]=Array("global","global \$cfg_basehost,\$cfg_cmsurl; if(!strstr(\$cfg_cmsurl,'http://')){@me = \$cfg_basehost.\$cfg_cmsurl;}else{@me = \$cfg_cmsurl;}",856,1044);
$z[3][4]=array();
$z[3][4]['name']="cfg_cmsurl";
$z[3][4]['runphp']="yes";

?>