<li>
									<a href=""[field:arcurl/]" class="hvr-shutter-out-horizontal"><img src="[field:litpic/]" title="xxx-name" class="img-responsive" alt=" " />
										<div class="w3l-action-icon"><i class="glyphicon glyphicon-play-circle" aria-hidden="true"></i></div>
									</a>
									<div class="wenzi">
										<div class="w3l-movie-text">
											<h6><a href=""[field:arcurl/]">[field:title/]</a></h6>
										</div>
										<div class="mid-2">
											<p>[field:pubdate function="GetDateTimeMK(@me)"/]</p>
										</div>
									</div>
									<div class="ribben"><p>NEW</p></div>
								</li>