<?php
$z[0]=Array("global","",144,176);
$z[0][4]=array();
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("global","",235,267);
$z[1][4]=array();
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("global","",313,345);
$z[2][4]=array();
$z[2][4]['name']="cfg_templets_skin";
$z[3]=Array("global","",376,408);
$z[3][4]=array();
$z[3][4]['name']="cfg_templets_skin";
$z[4]=Array("include","",691,723);
$z[4][4]=array();
$z[4][4]['file']="head.htm";
$z[5]=Array("arclist","\r\n							<li>\r\n								<a href=\"[field:arcurl/]\" class=\"hvr-shutter-out-horizontal\">\r\n									<img src=\"[field:litpic/]\" title=\"xxx-name\" class=\"img-responsive\" alt=\" \" />\r\n									<div class=\"w3l-action-icon\"><i class=\"glyphicon glyphicon-play-circle\" aria-hidden=\"true\"></i></div>\r\n								</a>\r\n								<div class=\"wenzi\">\r\n									<div class=\"w3l-movie-text\">\r\n										<h6><a href=\"[field:arcurl/]\">[field:title/]</a></h6>\r\n									</div>\r\n									<div class=\"mid-2\">\r\n										<p>[field:pubdate function=\"GetDateTimeMK(@me)\"/]</p>\r\n									</div>\r\n								</div>\r\n								<div class=\"ribben\"><p>NEW</p></div>\r\n							</li>\r\n						",1626,2349);
$z[5][4]=array();
$z[5][4]['limit']="3";
$z[5][4]['typeid']="2";
$z[5][4]['orderby']="id";
$z[5][4]['orderway']="desc";

?>