<?php
$z[0]=Array("global","",144,176);
$z[0][4]=array();
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("global","",235,267);
$z[1][4]=array();
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("global","",313,345);
$z[2][4]=array();
$z[2][4]['name']="cfg_templets_skin";
$z[3]=Array("global","",376,408);
$z[3][4]=array();
$z[3][4]['name']="cfg_templets_skin";
$z[4]=Array("include","",1127,1159);
$z[4][4]=array();
$z[4][4]['file']="head.htm";
$z[5]=Array("arclist","\r\n				<li class=\"in_bl mar_right_bot\">\r\n					<a href=\"[field:arcurl/]\" class=\"hvr-shutter-out-horizontal\">\r\n						<div class=\"\"><img src=\"[field:litpic/]\" title=\"xxx-name\" class=\"img-responsive img_radius\" alt=\" \" /></div>\r\n						<div class=\"w3l-action-icon\"><i class=\"glyphicon glyphicon-play-circle\" aria-hidden=\"true\"></i></div>\r\n					</a>\r\n					<h6><a href=\"[field:arcurl/]\">[field:title/]</a></h6>\r\n					<p>[field:pubdate function=\"GetDateTimeMK(@me)\"/]</p>\r\n				</li>\r\n			",1277,1834);
$z[5][4]=array();
$z[5][4]['limit']="5";
$z[5][4]['typeid']="2";
$z[5][4]['orderby']="id";
$z[5][4]['orderway']="desc";

?>